// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoFR0eDgtamgeXZZDIxMcJxaF3cO1Fuz0',
    appId: '1:579851181022:web:c5ed00ff20595ec3965b4f',
    messagingSenderId: '579851181022',
    projectId: 'note-beom',
    authDomain: 'note-beom.firebaseapp.com',
    databaseURL: 'https://note-beom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-beom.appspot.com',
    measurementId: 'G-NHN48Y94Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKuZ1F8vxhjDQeyLmuG2hllssegK99OjM',
    appId: '1:579851181022:android:e9ac4ff4fc282640965b4f',
    messagingSenderId: '579851181022',
    projectId: 'note-beom',
    databaseURL: 'https://note-beom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-beom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQZa2cI7eWpG9d5ZtjiT28zebpnRiUNQ',
    appId: '1:579851181022:ios:9d996db71b586006965b4f',
    messagingSenderId: '579851181022',
    projectId: 'note-beom',
    databaseURL: 'https://note-beom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-beom.appspot.com',
    iosClientId: '579851181022-6m2ujeg3p0e0j9f7o04jfsd67rjj8q57.apps.googleusercontent.com',
    iosBundleId: 'com.example.metroBeom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgQZa2cI7eWpG9d5ZtjiT28zebpnRiUNQ',
    appId: '1:579851181022:ios:9d996db71b586006965b4f',
    messagingSenderId: '579851181022',
    projectId: 'note-beom',
    databaseURL: 'https://note-beom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-beom.appspot.com',
    iosClientId: '579851181022-6m2ujeg3p0e0j9f7o04jfsd67rjj8q57.apps.googleusercontent.com',
    iosBundleId: 'com.example.metroBeom',
  );
}
